[package]
name = "par-sort"
version = "0.1.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
description = "Parallel sorting using Rayon"
readme = "README.md"
license = "Apache-2.0/MIT"

[dependencies]
rayon = "0.8.1"

[dev-dependencies]
rand = "0.3"
